{"uuid":"62c08325-8a4b-41f3-926e-e55efb61bfd4","historyId":"b3beb69545e6b9b45987fb777ecf4b2b","testCaseId":"[engine:junit-jupiter]/[class:addressbook.tests.ContactCreationTests]/[method:canAddContactInGroup()]","testCaseName":"canAddContactInGroup()","fullName":"addressbook.tests.ContactCreationTests.canAddContactInGroup","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:addressbook.tests.ContactCreationTests]/[method:canAddContactInGroup()]"},{"name":"host","value":"DESKTOP-901MQSB"},{"name":"thread","value":"18544@DESKTOP-901MQSB.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"addressbook.tests.ContactCreationTests"},{"name":"testClass","value":"addressbook.tests.ContactCreationTests"},{"name":"testMethod","value":"canAddContactInGroup"},{"name":"suite","value":"addressbook.tests.ContactCreationTests"}],"links":[],"name":"canAddContactInGroup()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"*[name='user']\"}\n  (Session info: chrome=119.0.6045.160)\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nBuild info: version: '4.13.0', revision: 'ba948ece5b*'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'\nDriver info: org.openqa.selenium.chrome.ChromeDriver\nCommand: [164f6e07304783f135dab0319a667fb4, findElement {using=name, value=user}]\nCapabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.160, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: C:\\Users\\Vlad\\AppData\\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52338}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52338/devtoo..., se:cdpVersion: 119.0.6045.160, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}\nSession ID: 164f6e07304783f135dab0319a667fb4","trace":"org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"*[name='user']\"}\n  (Session info: chrome=119.0.6045.160)\nFor documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nBuild info: version: '4.13.0', revision: 'ba948ece5b*'\nSystem info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8.1'\nDriver info: org.openqa.selenium.chrome.ChromeDriver\nCommand: [164f6e07304783f135dab0319a667fb4, findElement {using=name, value=user}]\nCapabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 119.0.6045.160, chrome: {chromedriverVersion: 119.0.6045.105 (38c72552c5e..., userDataDir: C:\\Users\\Vlad\\AppData\\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:52338}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:52338/devtoo..., se:cdpVersion: 119.0.6045.160, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}\nSession ID: 164f6e07304783f135dab0319a667fb4\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\r\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)\r\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)\r\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)\r\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)\r\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)\r\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)\r\n\tat org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)\r\n\tat org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:359)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:353)\r\n\tat addressbook.manager.HelperBase.click(HelperBase.java:15)\r\n\tat addressbook.manager.HelperBase.type(HelperBase.java:24)\r\n\tat addressbook.manager.LoginHelper.login(LoginHelper.java:12)\r\n\tat addressbook.manager.ApplicationManager.init(ApplicationManager.java:40)\r\n\tat addressbook.tests.TestBase.setUp(TestBase.java:24)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tSuppressed: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:66)\r\n\t\tat addressbook.tests.TestBase.checkDatabaseConsistency(TestBase.java:31)\r\n\t\t... 3 more\r\n\tCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)\r\n\t\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)\r\n\t\tat addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:58)\r\n\t\t... 4 more\r\n\tCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)\r\n\t\tat com.mysql.cj.NativeSession.connect(NativeSession.java:121)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809)\r\n\t\t... 10 more\r\n\tCaused by: java.net.ConnectException: Connection refused: connect\r\n\t\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:579)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:568)\r\n\t\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)\r\n\t\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\t\tat java.base/java.net.Socket.connect(Socket.java:639)\r\n\t\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)\r\n\t\t... 13 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1700622126252,"stop":1700622133701}