{"uuid":"7c3ba5e1-cdae-450e-a61f-6a5da66deac0","historyId":"8faa0a593b13fdf1c74c6a07d3dac0d","testCaseId":"[engine:junit-jupiter]/[class:addressbook.tests.GroupRemovalTests]/[method:canRemoveGroup()]","testCaseName":"canRemoveGroup()","fullName":"addressbook.tests.GroupRemovalTests.canRemoveGroup","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:addressbook.tests.GroupRemovalTests]/[method:canRemoveGroup()]"},{"name":"host","value":"DESKTOP-901MQSB"},{"name":"thread","value":"25084@DESKTOP-901MQSB.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"addressbook.tests.GroupRemovalTests"},{"name":"testClass","value":"addressbook.tests.GroupRemovalTests"},{"name":"testMethod","value":"canRemoveGroup"},{"name":"suite","value":"addressbook.tests.GroupRemovalTests"}],"links":[],"name":"canRemoveGroup()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]","trace":"org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:276)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\r\n\tat org.hibernate.boot.model.relational.Database.<init>(Database.java:45)\r\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:230)\r\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:198)\r\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:166)\r\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:125)\r\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:451)\r\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:102)\r\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:910)\r\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:960)\r\n\tat addressbook.manager.HibernateHelper.<init>(HibernateHelper.java:29)\r\n\tat addressbook.manager.ApplicationManager.hbm(ApplicationManager.java:72)\r\n\tat addressbook.tests.GroupRemovalTests.canRemoveGroup(GroupRemovalTests.java:13)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tSuppressed: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:66)\r\n\t\tat addressbook.tests.TestBase.checkDatabaseConsistency(TestBase.java:31)\r\n\t\t... 3 more\r\n\tCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)\r\n\t\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)\r\n\t\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)\r\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)\r\n\t\tat addressbook.manager.JdbcHelper.checkConsistency(JdbcHelper.java:58)\r\n\t\t... 4 more\r\n\tCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\r\n\t\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)\r\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)\r\n\t\tat com.mysql.cj.NativeSession.connect(NativeSession.java:121)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939)\r\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809)\r\n\t\t... 10 more\r\n\tCaused by: java.net.ConnectException: Connection refused: connect\r\n\t\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:579)\r\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:568)\r\n\t\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)\r\n\t\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\t\tat java.base/java.net.Socket.connect(Socket.java:639)\r\n\t\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)\r\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)\r\n\t\t... 13 more\r\nCaused by: org.hibernate.exception.JDBCConnectionException: Error calling DriverManager#getConnection [null]\r\n\tat org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:100)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator$1.convert(BasicConnectionCreator.java:107)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.convertSqlException(BasicConnectionCreator.java:132)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:39)\r\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:497)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:363)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:548)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:101)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:81)\r\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:135)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:354)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:236)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:82)\r\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:43)\r\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:129)\r\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)\r\n\t... 17 more\r\nCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)\r\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:819)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:440)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)\r\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)\r\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)\r\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:36)\r\n\t... 32 more\r\nCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\r\n\tat jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)\r\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\r\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\r\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)\r\n\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:166)\r\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)\r\n\tat com.mysql.cj.NativeSession.connect(NativeSession.java:121)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:939)\r\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:809)\r\n\t... 38 more\r\nCaused by: java.net.ConnectException: Connection refused: connect\r\n\tat java.base/sun.nio.ch.Net.connect0(Native Method)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:579)\r\n\tat java.base/sun.nio.ch.Net.connect(Net.java:568)\r\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)\r\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\tat java.base/java.net.Socket.connect(Socket.java:639)\r\n\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)\r\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)\r\n\t... 41 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1700622229986,"stop":1700622230010}